# DF line: func:toLobby   (reset a player into the lobby: out of round, full heal, clean inv, pad)
func('toLobby', tags={'Is Hidden': 'False'})
SetVar('=', var('%uuid in', 'unsaved'), num('0'))
PlayerAction('AdventureMode')
PlayerAction('SetMaxHealth', num('20'), tags={'Heal Player to Max Health': 'True'})
PlayerAction('SetFoodLevel', num('20'))
PlayerAction('ClearPotions')
PlayerAction('ClearInv', tags={'Clear Mode': 'Entire inventory', 'Clear Crafting and Cursor': 'True'})
PlayerAction('Teleport', loc(10.5, 51.0, 25.5, pitch=0.0, yaw=-90.0), tags={'Keep Velocity': 'False', 'Keep Current Rotation': 'False'})
