# DF line: process:arenaIn   (one per fighter: mark them in, survival kit, random arena drop)
process('arenaIn', tags={'Is Hidden': 'False'})
SetVar('=', var('%uuid in', 'unsaved'), num('1'))
SetVar('+=', var('%uuid rounds', 'saved'))
PlayerAction('SetMaxHealth', num('20'), tags={'Heal Player to Max Health': 'True'})
PlayerAction('SetFoodLevel', num('20'))
PlayerAction('ClearInv', tags={'Clear Mode': 'Entire inventory', 'Clear Crafting and Cursor': 'True'})
PlayerAction('GiveItems', item('{DF_NBT:4671,components:{"minecraft:custom_name":{extra:[{bold:0b,color:"#7DDFFF",italic:0b,obfuscated:0b,strikethrough:0b,text:"⚔ Arena Blade",underlined:0b}],text:""},"minecraft:lore":[{extra:[{bold:0b,color:"gray",italic:0b,obfuscated:0b,strikethrough:0b,text:"Last one standing wins.",underlined:0b}],text:""}],"minecraft:unbreakable":{}},count:1,id:"minecraft:iron_sword"}'))
PlayerAction('SurvivalMode')
SetVar('RandomLoc', var('drop', 'line'), loc(25.5, 51.0, 15.5), loc(45.5, 51.0, 35.5))
PlayerAction('Teleport', var('drop', 'line'), tags={'Keep Velocity': 'False', 'Keep Current Rotation': 'False'})
